carbon_api:
    resource: "@CarbonApiBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

storage:
    resource: "@AppBundle/Controller/Storage"
    type:     annotation

production:
    resource: "@AppBundle/Controller/Production"
    type:     annotation
