security:
    providers:
        db:
            id: uecode.api_key.provider.user_provider

    firewalls:

        authenticate:
            pattern: ^/authenticate$
            security: false
            stateless: true

        api:
            pattern: ^/
            api_key: true
            stateless: true
            provider: db # Required if you have multiple providers and firewalls

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        # - { path: ^/authenticate$, role: IS_AUTHENTICATED_ANONYMOUSLY }
