# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.type.user:
        class: AppBundle\Form\Type\UserFormType
        tags:
            - { name: form.type, alias: user }

    app.form.type.division:
        class: AppBundle\Form\Type\DivisionFormType
        tags:
            - { name: form.type, alias: division }

    app.form.type.sample:
        class: AppBundle\Form\Type\SampleFormType
        tags:
            - { name: form.type, alias: sample }
