# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.type.sample:
        class: AppBundle\Form\Type\SampleFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: sample }

    sample.importer:
        class: AppBundle\Service\SampleImporter

    sample.location_decider:
        class: AppBundle\Service\SampleLocationDecider
        arguments: ["@doctrine.orm.default_entity_manager"]

    sample.listener:
        class: AppBundle\Listener\SampleListener
        arguments: ["@logger"]
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }

    division.listener:
        class: AppBundle\Listener\DivisionListener
        arguments: ["@logger"]
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }

    app.form.type.division:
        class: AppBundle\Form\Type\DivisionFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: division }

    app.form.type.project:
        class: AppBundle\Form\Type\ProjectFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: project }
