# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.type.sample:
        class: AppBundle\Form\Type\Storage\SampleFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: sample }

    sample.importer:
        class: AppBundle\Service\SampleImporter
        arguments: ["@validator"]

    sample.location_decider:
        class: AppBundle\Service\SampleLocationDecider
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]

    division.manager:
        class: AppBundle\Service\Storage\DivisionManager
        arguments: ["@doctrine.orm.default_entity_manager"]

    sample.listener:
        class: AppBundle\Listener\Storage\SampleListener
        arguments: ["@logger"]
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    division.listener:
        class: AppBundle\Listener\Storage\DivisionListener
        arguments: ["@logger"]
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    division.serializer.listener:
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
        class: AppBundle\Listener\Storage\DivisionSerializerListener
        tags:
            - { name: jms_serializer.event_subscriber }

    app.form.type.division:
        class: AppBundle\Form\Type\Storage\DivisionFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: division }

    app.form.type.project:
        class: AppBundle\Form\Type\ProjectFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: project }

    app.validator.storage_location_validator:
        class: AppBundle\Validator\Constraints\StorageLocationValidator
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
        tags:
            - { name: validator.constraint_validator, alias: storage_location_validator }

    app.form.type.dna_request:
        class: AppBundle\Form\Type\Production\DNARequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: DNA }

    app.form.type.protein_request:
        class: AppBundle\Form\Type\Production\ProteinRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: Protein }

    app.form.type.purification_request:
        class: AppBundle\Form\Type\Production\PurificationRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: Purification }

    app.form.type.affinity_purification_request:
        class: AppBundle\Form\Type\Production\AffinityPurificationRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: 'AffinityPurification' }

    app.form.type.size_exclusion_purification_request:
        class: AppBundle\Form\Type\Production\SizeExclusionPurificationRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: 'SizeExclusionPurification' }

    app.form.type.native_gel_request:
        class: AppBundle\Form\Type\Production\NativeGelRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: NativeGel }

    app.form.type.western_gel_request:
        class: AppBundle\Form\Type\Production\WesternGelRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: WesternGel }

    app.form.type.sds_page_request:
        class: AppBundle\Form\Type\Production\SdsPageRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: SdsPage }

    app.form.type.sec_mals_request:
        class: AppBundle\Form\Type\Production\SecMalsRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: SecMals }

    app.form.type.spr_request:
        class: AppBundle\Form\Type\Production\SprRequestFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: Spr }

    app.form.type.protocol:
        class: AppBundle\Form\Type\ProtocolFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: protocol }

    app.form.type.pipeline:
        class: AppBundle\Form\Type\Production\PipelineFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: pipeline }

    app.form.type.pipeline_steps:
        class: AppBundle\Form\Type\Production\PipelineStepsFormType
        arguments: ["@doctrine.orm.default_entity_manager", "@form.factory"]
        tags:
            - { name: form.type, alias: pipeline_steps }

    app.form.type.tag:
        class: AppBundle\Form\Type\Storage\TagFormType
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type, alias: tag }
