services:
#    carbon_api.example:
#        class: Carbon\ApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
   carbon_api.query_builder:
       class: Carbon\ApiBundle\Service\QueryBuilder
       # arguments: [@service_id, "plain_value", %parameter%]
