services:
#    carbon_api.example:
#        class: Carbon\ApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

   carbon_api.grid:
       class: Carbon\ApiBundle\Grid\CarbonGrid
       arguments: [@request_stack, @carbon_api.annotation_reader, @doctrine.orm.default_entity_manager]

   carbon_api.serialization_helper:
       class: Carbon\ApiBundle\Service\SerializationHelper
       arguments: [@jms_serializer, @request_stack]

   carbon_api.annotation_reader:
       class: Carbon\ApiBundle\Service\CarbonAnnotationReader
