<?php

namespace AppBundle\Entity\Storage;

use Doctrine\ORM\EntityRepository;

/**
 * ProtocolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocolRepository extends EntityRepository
{
}
